'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import { enrollCourse, getCourses, getCourseListings, getCampusSlug, getMyCourses, unenrollCourse, type Listing } from '../../lib/api';

type Course = { id:number; code:string; name:string; semester:string; campus_slug?:string };
export default function CoursesPage(){
  const [courses,setCourses]=useState<Course[]>([]); const [mine,setMine]=useState<Course[]>([]); const [selected,setSelected]=useState<number|null>(null); const [listings,setListings]=useState<Listing[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState<number|null>(null);
  const load=async()=>{try{const slug=getCampusSlug(); const [all,owned]=await Promise.all([getCourses(slug),getMyCourses(slug)]);setCourses(all);setMine(owned);if(owned[0]){setSelected(owned[0].id);setListings(await getCourseListings(owned[0].id));}}catch(e){setError(e instanceof Error?e.message:'Unable to load courses')}};
  useEffect(()=>{void load()},[]);
  const toggle=async(c:Course)=>{setBusy(c.id);try{const enrolled=mine.some(x=>x.id===c.id);if(enrolled)await unenrollCourse(c.id);else await enrollCourse(c.id);const owned=await getMyCourses(getCampusSlug());setMine(owned);if(!enrolled){setSelected(c.id);setListings(await getCourseListings(c.id))}else if(selected===c.id){setSelected(owned[0]?.id||null);setListings(owned[0]?await getCourseListings(owned[0].id):[]);}}catch(e){setError(e instanceof Error?e.message:'Unable to update course')}finally{setBusy(null)}};
  return <AppShell active="Courses"><div className="page-header"><div><div className="eyebrow">MY ACADEMICS</div><h1>Courses</h1><p className="muted small">Follow your courses and see marketplace items tagged for them.</p></div><Link className="btn btn-ghost" href="/marketplace">Browse marketplace</Link></div>{error&&<div className="error-box">{error}</div>}<section className="panel"><div className="panel-head"><h2>My courses</h2><span className="muted small">{mine.length} enrolled</span></div><div className="course-strip">{mine.map(c=><button className="course-chip" key={c.id} onClick={()=>{setSelected(c.id);getCourseListings(c.id).then(setListings).catch(()=>setListings([]))}}>{c.code}</button>)}{!mine.length&&<div className="empty-state"><strong>No courses enrolled</strong><span>Choose courses below to personalize your campus marketplace.</span></div>}</div></section><section className="panel" style={{marginTop:18}}><div className="panel-head"><h2>Course catalog</h2><span className="muted small">Select courses you take</span></div>{courses.map(c=>{const enrolled=mine.some(x=>x.id===c.id);return <div className="seller-list-row" key={c.id}><div><strong>{c.code} · {c.name}</strong><div className="muted small">{c.semester || 'Current semester'}</div></div><button className={enrolled?'btn btn-ghost':'btn btn-primary'} disabled={busy===c.id} onClick={()=>toggle(c)}>{busy===c.id?'Saving...':enrolled?'Remove':'Enroll'}</button></div>})}</section>{selected&&<section className="panel" style={{marginTop:18}}><div className="panel-head"><h2>Listings for {mine.find(c=>c.id===selected)?.code}</h2><Link href="/seller/new">Sell one →</Link></div>{listings.length?<div className="product-grid-v2">{listings.map(l=><Link href={`/marketplace/${l.id}`} className="wanted-card" key={l.id}><h3>{l.title}</h3><div className="wanted-meta"><span>₹{Number(l.price).toLocaleString('en-IN')}</span><span>{l.condition}</span></div><p>{l.description || 'Course-related marketplace listing.'}</p></Link>)}</div>:<div className="empty-state"><strong>No tagged listings yet</strong><span>Sellers can tag listings to this course from Seller Studio when publishing or editing.</span></div>}</section>}</AppShell>;
}
