'use client';
import Link from 'next/link';
import { Suspense, useState } from 'react';
import { useRouter } from 'next/navigation';
import Logo from '../../components/Logo';
import { requestPasswordResetOtp, resetPassword, verifyOtp } from '../../lib/api';

function ForgotPasswordContent(){
  const router=useRouter();
  const [step,setStep]=useState<'request'|'verify'|'reset'>('request'); const [channel,setChannel]=useState<'email'|'phone'>('email'); const [destination,setDestination]=useState(''); const [digits,setDigits]=useState(''); const [token,setToken]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [devCode,setDevCode]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const send=async()=>{setBusy(true);setError('');try{const r=await requestPasswordResetOtp(channel,destination);const code=r.otp_delivery?.debug_code||'';setDevCode(code);if(code)localStorage.setItem('campuscart_otp_debug',code);setStep('verify')}catch(e){setError(e instanceof Error?e.message:'Unable to send reset code')}finally{setBusy(false)}};
  const verify=async()=>{setBusy(true);setError('');try{const r=await verifyOtp({channel,destination,code:digits,purpose:'password_reset'});if(!r.reset_token)throw new Error('Reset token was not returned');setToken(r.reset_token);setStep('reset')}catch(e){setError(e instanceof Error?e.message:'Invalid reset code')}finally{setBusy(false)}};
  const update=async()=>{if(password.length<8||password!==confirm){setError(password.length<8?'Password must be at least 8 characters':'Passwords do not match');return}setBusy(true);setError('');try{await resetPassword(token,password);router.push('/login')}catch(e){setError(e instanceof Error?e.message:'Unable to reset password')}finally{setBusy(false)}};
  return <main className="auth-page"><div className="auth-card"><div className="auth-brand"><Logo/><div><div className="eyebrow" style={{color:'#bcaeff'}}>ACCOUNT RECOVERY</div><h2>Reset your CampusCart password.</h2><p>Verify the contact on your account, then choose a new password.</p></div></div><div className="auth-form">{step==='request'&&<><div className="eyebrow">STEP 1</div><h2>Send reset code</h2><div className="auth-tabs"><button className={channel==='email'?'auth-tab active':'auth-tab'} onClick={()=>setChannel('email')}>Email</button><button className={channel==='phone'?'auth-tab active':'auth-tab'} onClick={()=>setChannel('phone')}>Phone</button></div><label>{channel==='email'?'Email address':'Phone number'}<input value={destination} onChange={e=>setDestination(e.target.value)} /></label><button className="btn btn-primary full" disabled={busy||!destination} onClick={send}>{busy?'Sending...':'Send reset code'}</button></>}{step==='verify'&&<><div className="eyebrow">STEP 2</div><h2>Enter the code</h2><label>6-digit OTP<input inputMode="numeric" maxLength={6} value={digits} onChange={e=>setDigits(e.target.value.replace(/\D/g,'').slice(0,6))}/></label>{devCode&&<div className="success-box">Development OTP: <strong>{devCode}</strong></div>}<button className="btn btn-primary full" disabled={busy||digits.length!==6} onClick={verify}>{busy?'Verifying...':'Verify code'}</button></>}{step==='reset'&&<><div className="eyebrow">STEP 3</div><h2>Choose a new password</h2><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label><button className="btn btn-primary full" disabled={busy} onClick={update}>{busy?'Updating...':'Update password'}</button></>}{error&&<div className="error-box">{error}</div>}<div className="auth-foot"><Link href="/login">Back to sign in</Link></div></div></div></main>;
}
export default function ForgotPasswordPage(){return <Suspense fallback={<main className="auth-page"><div className="auth-card"><div className="auth-form">Loading...</div></div></main>}><ForgotPasswordContent/></Suspense>}
