
'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Logo from './Logo';
type NavItem=[string,string,string];
const campusLinks:NavItem[]=[['⌂','Home','/campus'],['⌕','Marketplace','/marketplace'],['?','Wanted','/wanted'],['⇄','Smart Swap','/swap'],['◒','Demand Radar','/demand'],['⌖','Lost & Found','/lost-found']];
const activityLinks:NavItem[]=[['✉','Messages','/messages'],['↗','Transactions','/transactions'],['●','Notifications','/notifications'],['▦','Courses','/courses']];
const tradingLinks:NavItem[]=[['₹','Offers','/seller?tab=offers'],['＋','My Listings','/seller'],['♡','Saved Items','/saved']];
function NavGroup({label,items,active}:{label:string;items:NavItem[];active:string}){return <div className="side-group"><div className="side-label">{label}</div>{items.map(([icon,title,href])=><Link key={title} className={active===title?'side-link active':'side-link'} href={href}><span className="side-icon">{icon}</span><span className="side-link-label">{title}</span></Link>)}</div>}
export default function Sidebar({active='Home'}:{active?:string}){const [campus,setCampus]=useState('Campus');const [role,setRole]=useState('student');useEffect(()=>{setCampus(localStorage.getItem('campuscart_campus')||'Campus');try{setRole(JSON.parse(localStorage.getItem('campuscart_user')||'{}')?.role||'student')}catch{}},[]);const homeHref=campus!=='Campus'?`/campus/${campus}`:'/campus';const links=campusLinks.map(([icon,title,href])=>title==='Home'?[icon,title,homeHref] as NavItem:[icon,title,href] as NavItem);return <aside className="sidebar"><div className="sidebar-top"><Logo/><div className="sidebar-campus"><span className="campus-dot"/> {campus} <span>⌄</span></div></div><nav className="sidebar-nav" aria-label="CampusCart navigation"><NavGroup label="Campus" items={links} active={active}/><NavGroup label="Activity" items={activityLinks} active={active}/><NavGroup label="Your CampusCart" items={tradingLinks} active={active}/>{role==='admin'&&<div className="side-group"><div className="side-label">Admin</div><Link className={active==='Admin'?'side-link active':'side-link'} href="/admin"><span className="side-icon">◆</span><span className="side-link-label">Admin Console</span></Link></div>}</nav><div className="side-bottom"><Link className={active==='Profile'?'side-link active':'side-link'} href="/profile"><span className="side-icon">◉</span><span className="side-link-label">Profile</span></Link></div></aside>}
