'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import AppShell from '../../../../components/AppShell';
import { attachListingImage, deleteListingImage, getAddresses, getCampus, getCampusSlug, getCourses, getListing, getListingCourses, updateListing, uploadListingImage, type Address, type Campus, type Listing } from '../../../../lib/api';

type Course = { id:number; code:string; name:string; semester:string; campus_slug?:string };
export default function EditListingPage() {
  const params = useParams<{ id: string }>(); const router = useRouter();
  const [listing, setListing] = useState<Listing | null>(null); const [campus, setCampus] = useState<Campus | null>(null); const [addresses, setAddresses] = useState<Address[]>([]); const [courses,setCourses]=useState<Course[]>([]); const [selectedCourses,setSelectedCourses]=useState<number[]>([]);
  const [title,setTitle]=useState(''); const [category,setCategory]=useState('Academic Supplies'); const [condition,setCondition]=useState('good'); const [listingType,setListingType]=useState('sell'); const [price,setPrice]=useState(''); const [description,setDescription]=useState(''); const [pickupArea,setPickupArea]=useState(''); const [landmark,setLandmark]=useState(''); const [pickupInstructions,setPickupInstructions]=useState(''); const [addressId,setAddressId]=useState('');
  const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{const id=Number(params.id);const slug=getCampusSlug();if(!id||!slug)return;Promise.all([getListing(id),getCampus(slug),getAddresses(),getCourses(slug),getListingCourses(id)]).then(([item,c,as,cs,attached])=>{setListing(item);setCampus(c);setAddresses(as);setCourses(cs);setSelectedCourses(attached.map(x=>x.id));setTitle(item.title);setCategory(item.category);setCondition(item.condition);setListingType(item.listing_type);setPrice(String(item.price));setDescription(item.description);setPickupArea(item.pickup_area||'');setLandmark(item.pickup_landmark||'');setPickupInstructions(item.pickup_instructions||'');setAddressId('');}).catch(e=>setError(e instanceof Error?e.message:'Unable to load listing'))},[params.id]);
  const save=async()=>{if(!listing)return;setBusy(true);setError('');try{await updateListing(listing.id,{title,category,condition,listing_type:listingType,price:listingType==='giveaway'?0:Number(price),description,pickup_location_id:pickupArea?campus?.pickup_locations?.find(x=>x.name===pickupArea)?.id:undefined,pickup_address_id:addressId?Number(addressId):undefined,pickup_area:pickupArea,pickup_landmark:landmark,pickup_instructions:pickupInstructions,course_ids:selectedCourses});router.push('/seller')}catch(e){setError(e instanceof Error?e.message:'Unable to save listing')}finally{setBusy(false)}};
  const addPhotos=async(files:FileList|null)=>{if(!listing||!files?.length)return;setUploading(true);setError('');try{const remaining=6-(listing.images?.length||0);for(const file of Array.from(files).slice(0,remaining)){const up=await uploadListingImage(file);await attachListingImage(listing.id,{url:up.url,alt:title||file.name,sort_order:listing.images.length});setListing(await getListing(listing.id))}}catch(e){setError(e instanceof Error?e.message:'Unable to add photo')}finally{setUploading(false)}};
  const removePhoto=async(imageId?:number)=>{if(!listing||imageId==null)return;setError('');try{await deleteListingImage(listing.id,imageId);setListing(await getListing(listing.id))}catch(e){setError(e instanceof Error?e.message:'Unable to remove photo')}};
  return <AppShell active="My Listings"><div className="page-header"><div><div className="eyebrow">SELLER STUDIO</div><h1>Edit listing</h1><p className="muted small">Update details, photos and course tags without recreating the listing.</p></div></div>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<section className="panel"><div className="form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Academic Supplies</option><option>Books</option><option>Electronics</option><option>Furniture</option><option>Clothing</option><option>Hostel Essentials</option></select></label><label>Condition<select value={condition} onChange={e=>setCondition(e.target.value)}><option value="new">New</option><option value="like-new">Like new</option><option value="good">Good</option><option value="fair">Fair</option></select></label><label>Listing type<select value={listingType} onChange={e=>setListingType(e.target.value)}><option value="sell">Sell</option><option value="rent">Rent</option><option value="giveaway">Give away</option></select></label><label>Price<input inputMode="numeric" value={price} disabled={listingType==='giveaway'} onChange={e=>setPrice(e.target.value.replace(/[^0-9.]/g,''))}/></label><label>Saved pickup address<select value={addressId} onChange={e=>setAddressId(e.target.value)}><option value="">Keep current / no private address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} · {a.locality}, {a.city}</option>)}</select></label><label className="span-2">Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Campus pickup point<select value={pickupArea} onChange={e=>setPickupArea(e.target.value)}><option value="">Select a campus point</option>{campus?.pickup_locations?.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>Landmark<input value={landmark} onChange={e=>setLandmark(e.target.value)}/></label><label className="span-2">Pickup instructions<textarea value={pickupInstructions} onChange={e=>setPickupInstructions(e.target.value)} maxLength={500}/></label></div>
  {courses.length>0&&<div className="panel" style={{marginTop:14,padding:14}}><div className="eyebrow">COURSE TAGS</div><strong>Relevant courses</strong><div className="category-row">{courses.map(c=><button type="button" key={c.id} className={selectedCourses.includes(c.id)?'category-chip active':'category-chip'} onClick={()=>setSelectedCourses(x=>x.includes(c.id)?x.filter(id=>id!==c.id):[...x,c.id])}>{c.code}</button>)}</div></div>}
  <div style={{marginTop:18}}><div className="panel-head"><h2>Photos</h2><label className="btn btn-ghost" style={{cursor:uploading?'default':'pointer'}}><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple hidden disabled={uploading||(listing?.images?.length||0)>=6} onChange={e=>{void addPhotos(e.target.files);e.currentTarget.value='';}}/>{uploading?'Uploading…':'＋ Add photos'}</label></div><div className="photo-strip">{listing?.images?.map((image:any,i)=><div key={image.id||image.url} style={{position:'relative'}}><img src={image.url} alt={image.alt||title}/><button type="button" className="btn btn-ghost" aria-label={`Remove photo ${i+1}`} style={{position:'absolute',right:4,top:4,padding:'3px 7px'}} disabled={(listing.images?.length||0)<=1} onClick={()=>removePhoto(image.id)}>×</button></div>)}</div>{listing?.images?.length===1&&<div className="hint">Keep at least one photo on every active listing.</div>}</div>
  <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button className="btn btn-ghost" onClick={()=>router.back()}>Cancel</button><button className="btn btn-primary" disabled={busy||!title.trim()||(listingType!=='giveaway'&&!price)} onClick={save}>{busy?'Saving...':'Save changes'}</button></div></section></AppShell>;
}
