'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import AppShell from '../../components/AppShell';
import { closeWanted, createConversation, createWanted, getCampusSlug, getWantedMatches, listWanted, type WantedPost } from '../../lib/api';
type Match={listing_id:number;score:number;reason:string};
export default function Wanted(){
  const [posts,setPosts]=useState<WantedPost[]>([]);const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [category,setCategory]=useState('Books');const [description,setDescription]=useState('');const [budget,setBudget]=useState('');const [neededBy,setNeededBy]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState<number|null>(null);const [matches,setMatches]=useState<Record<number,Match[]>>({});
  const load=()=>listWanted(getCampusSlug()).then(setPosts).catch(e=>setError(e instanceof Error?e.message:'Unable to load wanted posts'));useEffect(()=>{void load()},[]);
  const submit=async()=>{setBusy(-1);setError('');try{const [a,b]=budget.split('-').map(x=>Number(x.trim()));await createWanted({campus_slug:getCampusSlug(),title,category,description,budget_min:a||undefined,budget_max:b||undefined,needed_by:neededBy||undefined});setTitle('');setDescription('');setBudget('');setNeededBy('');setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create request')}finally{setBusy(null)}};
  const showMatches=async(id:number)=>{setBusy(id);setError('');try{const found=await getWantedMatches(id);setMatches(m=>({...m,[id]:found}))}catch(e){setError(e instanceof Error?e.message:'Unable to load matches')}finally{setBusy(null)}};
  const close=async(id:number)=>{setBusy(id);try{await closeWanted(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to close request')}finally{setBusy(null)}};
  const messageSeller=async(listingId:number)=>{try{const c=await createConversation(listingId); window.location.href=`/messages?conversation=${c.id}`;}catch(e){setError(e instanceof Error?e.message:'Unable to open seller conversation')}};
  return <AppShell active="Wanted"><div className="page-header"><div><div className="eyebrow">DEMAND BOARD</div><h1>Wanted</h1><p className="muted small" style={{marginTop:4}}>Students post what they need so verified campus sellers can respond.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}>＋ Post a request</button></div>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}
    {open&&<div className="panel wanted-form"><div className="eyebrow">POST A REQUEST</div><h2>What are you looking for?</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. DBMS textbook"/></label><div className="form-grid"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Books</option><option>Electronics</option><option>Academic Supplies</option><option>Clothing</option><option>Furniture</option></select></label><label>Budget range<input value={budget} onChange={e=>setBudget(e.target.value)} placeholder="300-500"/></label><label>Needed by<input type="date" value={neededBy} onChange={e=>setNeededBy(e.target.value)}/></label><label className="span-2">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mention edition, size, model, preferred condition or other details."/></label></div><div style={{display:'flex',gap:8,marginTop:12}}><button className="btn btn-primary" disabled={busy!==null||!title.trim()} onClick={submit}>{busy===-1?'Posting...':'Post request'}</button><button className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button></div></div>}
    <div className="panel"><div className="product-grid-v2">{posts.map(p=><article key={p.id} className="wanted-card"><div className="eyebrow">{p.category} · {p.status}</div><h3>{p.title}</h3><div className="wanted-meta"><span>{p.budget_min!=null&&p.budget_max!=null?`₹${p.budget_min}–₹${p.budget_max}`:'Budget open'}</span><span>{p.needed_by?`Needed by ${new Date(p.needed_by).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}`:'No deadline'}</span></div><p>{p.description||'A verified student is looking for this item on campus.'}</p>{p.is_owner?<><button className="btn btn-soft full" disabled={busy===p.id} onClick={()=>showMatches(p.id)}>{busy===p.id?'Finding matches...':'Find matching listings'}</button><button className="btn btn-ghost full" style={{marginTop:8}} disabled={busy===p.id} onClick={()=>close(p.id)}>Close request</button>{matches[p.id]?.length?<div className="hint" style={{marginTop:10}}>{matches[p.id].slice(0,5).map(m=><div key={m.listing_id} style={{display:'flex',justifyContent:'space-between',gap:8,marginBottom:5}}><span>#{m.listing_id} · {m.score}% · {m.reason}</span><span style={{display:'flex',gap:8}}><Link href={`/marketplace/${m.listing_id}`}>View</Link><button className="card-link" onClick={()=>void messageSeller(m.listing_id)}>Message seller</button></span></div>)}</div>:null}</>:<button className="btn btn-soft full" onClick={()=>window.location.href=`/marketplace?search=${encodeURIComponent(p.title)}`}>I have this → marketplace</button>}</article>)}</div>{!posts.length&&<div className="empty-state"><strong>No open requests yet</strong><span>Post the first request for your campus.</span></div>}</div>
  </AppShell>;
}
