'use client';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import { claimLostFound, closeLostFound, confirmLostFoundClaim, createLostFound, getCampusSlug, listLostFound, rejectLostFoundClaim, type LostFoundItem } from '../../lib/api';

export default function LostFound() {
  const [items,setItems]=useState<LostFoundItem[]>([]); const [type,setType]=useState(''); const [open,setOpen]=useState(false); const [itemType,setItemType]=useState('found'); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [location,setLocation]=useState(''); const [date,setDate]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState<number|null>(null); const [claimNote,setClaimNote]=useState(''); const [claiming,setClaiming]=useState<number|null>(null);
  const load=()=>listLostFound(getCampusSlug(),type).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Unable to load lost & found')); useEffect(()=>{void load()},[type]);
  const submit=async()=>{setBusy(-1);setError('');try{await createLostFound({campus_slug:getCampusSlug(),item_type:itemType,title,description,location_text:location,item_date:date||undefined});setTitle('');setDescription('');setLocation('');setDate('');setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to post item')}finally{setBusy(null)}};
  const act=async(id:number,fn:()=>Promise<unknown>)=>{setBusy(id);setError('');try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update item')}finally{setBusy(null)}};
  return <AppShell active="Lost & Found"><div className="page-header"><div><div className="eyebrow">CAMPUS SERVICE</div><h1>Lost & Found</h1><p className="muted small" style={{marginTop:4}}>Verified campus members can post items, submit claims and confirm resolutions.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}>＋ Post item</button></div>
    <div className="category-row">{['','lost','found'].map(x=><button key={x||'all'} className={type===x?'category-chip active':'category-chip'} onClick={()=>setType(x)}>{x?x[0].toUpperCase()+x.slice(1):'All'}</button>)}</div>{error&&<div className="error-box">{error}</div>}
    {open&&<div className="panel wanted-form"><div className="eyebrow">POST ITEM</div><h2>What happened?</h2><div className="form-grid"><label>Type<select value={itemType} onChange={e=>setItemType(e.target.value)}><option value="found">Found</option><option value="lost">Lost</option></select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="span-2">Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Black scientific calculator"/></label><label className="span-2">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Distinctive details that help identify the item."/></label><label className="span-2">Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Library, north entrance"/></label></div><div style={{display:'flex',gap:8,marginTop:12}}><button className="btn btn-primary" disabled={busy!==null||!title.trim()} onClick={submit}>{busy===-1?'Posting...':'Post item'}</button><button className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button></div></div>}
    <section className="panel"><div className="product-grid-v2">{items.map(item=><article className="wanted-card" key={item.id}><div className="eyebrow">{item.item_type} · {item.status}</div><h3>{item.title}</h3><p>{item.description||'No extra description provided.'}</p><div className="wanted-meta"><span>📍 {item.location_text||'Campus'}</span><span>{item.item_date||'Date not given'}</span></div>{item.is_owner&&item.status==='claimed'&&item.claimant_id?<div className="success-box"><strong>Claim pending confirmation.</strong><br/>A verified student has submitted a claim for this found item.{item.claim_message?<><br/><span className="small">Claim note: {item.claim_message}</span></>:null}</div>:null}{item.is_owner&&item.status==='claimed'&&item.claimant_id?<div style={{display:'flex',gap:8,marginTop:10}}><button className="btn btn-primary" disabled={busy===item.id} onClick={()=>act(item.id,()=>confirmLostFoundClaim(item.id))}>Confirm claim</button><button className="btn btn-ghost" disabled={busy===item.id} onClick={()=>act(item.id,()=>rejectLostFoundClaim(item.id))}>Reject claim</button></div>:item.is_owner&&item.status!=='closed'?<button className="btn btn-ghost full" disabled={busy===item.id} onClick={()=>act(item.id,()=>closeLostFound(item.id))}>{busy===item.id?'Updating...':'Mark resolved'}</button>:!item.is_owner&&item.item_type==='found'&&item.status==='open'?<><textarea value={claiming===item.id?claimNote:''} onChange={e=>{setClaiming(item.id);setClaimNote(e.target.value)}} placeholder="Why do you believe this is yours? Include identifying details." style={{width:'100%',marginTop:10}}/><button className="btn btn-soft full" disabled={busy===item.id||claiming!==item.id} onClick={()=>{const note=claimNote; setClaimNote(''); setClaiming(null); void act(item.id,()=>claimLostFound(item.id,note))}}>{busy===item.id?'Claiming...':'Submit claim'}</button></>:item.status==='claimed'&&!item.is_owner?<div className="hint">A claim is pending. The poster must confirm the match.</div>:<div className="hint">{item.status==='closed'?'Resolved.':'Only verified campus members can interact with this post.'}</div>}</article>)}</div>{!items.length&&<div className="empty-state"><strong>No matching posts</strong><span>Be the first to post a lost or found item for your campus.</span></div>}</section>
  </AppShell>;
}
