'use client';
import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import ProductCard from '../../components/ProductCard';
import PillSelect from '../../components/PillSelect';
import { getCampus, getCampusSlug, getMarketplace, trackEvent, type Campus, type Listing } from '../../lib/api';
import { useSearchParams } from 'next/navigation';
const categories=['All','Books','Electronics','Hostel Essentials','Furniture','Clothing','Academic Supplies'];
export default function Marketplace(){const params=useSearchParams();const initialQuery=params.get('search')||'';const [query,setQuery]=useState(initialQuery);const [cat,setCat]=useState('All');const [condition,setCondition]=useState('Any condition');const [price,setPrice]=useState('Any price');const [distance,setDistance]=useState('Any distance');const [sort,setSort]=useState('Recommended');const [list,setList]=useState<Listing[]>([]);const [campus,setCampus]=useState<Campus|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{const slug=getCampusSlug();if(!slug){setLoading(false);setError('Choose a verified campus first.');return}getCampus(slug).then(setCampus).catch(()=>{});},[]);
useEffect(()=>{const t=setTimeout(()=>{const slug=getCampusSlug();if(!slug)return;const opts:{search?:string;category?:string;condition?:string;minPrice?:string;maxPrice?:string;sort?:string}={search:query,category:cat==='All'||cat==='Category'?'':cat,condition:condition==='Any condition'?'':condition,sort:sort==='Recommended'?'recommended':sort==='Newest'?'newest':sort==='Closest'?'closest':sort==='Lowest price'?'price_low':'recommended'};if(price==='Under ₹500')opts.maxPrice='500';if(price==='₹500–₹2,000'){opts.minPrice='500';opts.maxPrice='2000'}if(price==='₹2,000+')opts.minPrice='2000';trackEvent('search',slug,undefined,cat==='All'?'':cat,query).catch(()=>{});setLoading(true);getMarketplace(slug,opts).then(setList).catch(e=>setError(e instanceof Error?e.message:'Unable to load marketplace')).finally(()=>setLoading(false));},180);return()=>clearTimeout(t)},[query,cat,condition,price,distance,sort]);
const shown=useMemo(()=>{if(distance==='Any distance')return list;const max=distance==='Under 1 km'?1:3;return list.filter(x=>x.distance_km==null||Number(x.distance_km)<=max)},[distance,list]);
return <AppShell active="Marketplace"><div className="page-header"><div><div className="eyebrow">CAMPUS MARKETPLACE</div><h1>Marketplace</h1><p className="muted small">{campus?`${campus.name} · ${campus.city}, ${campus.state}`:'Your verified campus'}</p></div><div className="page-actions"><span className="verified-badge">✓ Verified campus</span></div></div>{error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}<div className="search-strip"><input value={query} onChange={e=>setQuery(e.target.value)} className="search-input" placeholder="Search for items, categories or brands..."/><PillSelect label="Category" options={categories.slice(1)} value={cat==='All'?'Category':cat} onChange={setCat}/><PillSelect label="Condition" options={['Any condition','New','Like new','Good','Fair']} value={condition} onChange={setCondition}/><PillSelect label="Price" options={['Any price','Under ₹500','₹500–₹2,000','₹2,000+']} value={price} onChange={setPrice}/><PillSelect label="Distance" options={['Any distance','Under 1 km','Under 3 km']} value={distance} onChange={setDistance}/><PillSelect label="Sort" options={['Recommended','Newest','Closest','Lowest price']} value={sort} onChange={setSort}/></div><div className="category-row">{categories.map(c=><button key={c} onClick={()=>setCat(c)} className={cat===c?'category-chip active':'category-chip'}><span className="category-icon">{c==='Books'?'📚':c==='Electronics'?'◈':c==='Furniture'?'⌂':c==='Clothing'?'◌':c==='All'?'✦':'•'}</span>{c}</button>)}</div><div className="market-toolbar"><strong>{loading?'Loading...':`${shown.length} results`}</strong><span className="muted small">Recommended within your verified campus</span></div><div className="product-grid-v2">{shown.map(p=><ProductCard key={p.id} listing={p}/>)}</div>{!loading&&!shown.length&&<div className="empty-state"><strong>No listings match these filters.</strong><span>Try a broader search, category or price range.</span></div>}</AppShell>;}
