'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import { approveCampusMember, createAdminCourse, getAdminAuditLogs, getAdminCampuses, getAdminCourses, getAdminListings, getAdminMembers, getAdminTransactions, getAdminUsers, getReports, moderateListing, resolveReport, revokeCampusMember, setAdminUserStatus, type Campus } from '../../lib/api';

type Member={id:number;user_id:number;name:string;email:string;phone?:string|null;campus_name:string;verification_method:string;verified:boolean;joined_at:string};
type UserRow={id:number;name:string;email:string;phone?:string|null;role:string;active:boolean;email_verified:boolean;phone_verified:boolean;created_at:string};
type Tx={id:number;listing_id:number;listing_title:string;buyer_name:string;buyer_email:string;seller_id:number;agreed_price:number;status:string;created_at:string};
type Report={id:number;reporter_id:number;target_type:string;target_id:number;reason:string;notes:string;status:string;created_at:string};
type ListingRow={id:number;title:string;seller_name:string;campus_name:string;price:number;status:string;created_at:string};
type AuditRow={id:number;actor_user_id?:number|null;action:string;resource_type:string;resource_id:string;detail:string;created_at:string};
type CourseRow={id:number;campus_id:number;code:string;name:string;semester:string};
export default function Admin(){
 const [members,setMembers]=useState<Member[]>([]);const [allMembers,setAllMembers]=useState<Member[]>([]);const [users,setUsers]=useState<UserRow[]>([]);const [txs,setTxs]=useState<Tx[]>([]);const [reports,setReports]=useState<Report[]>([]);const [listings,setListings]=useState<ListingRow[]>([]);const [logs,setLogs]=useState<AuditRow[]>([]);const [campuses,setCampuses]=useState<Campus[]>([]);const [courses,setCourses]=useState<CourseRow[]>([]);const [selectedCampus,setSelectedCampus]=useState<number|null>(null);const [courseForm,setCourseForm]=useState({code:'',name:'',semester:''});const [userQuery,setUserQuery]=useState('');const [listingQuery,setListingQuery]=useState('');const [txQuery,setTxQuery]=useState('');const [logQuery,setLogQuery]=useState('');const [busy,setBusy]=useState<number|null>(null);const [error,setError]=useState('');
 const load=async()=>{try{const [m,am,u,t,r,l,a,cs]=await Promise.all([getAdminMembers(undefined,true),getAdminMembers(undefined,false),getAdminUsers(userQuery),getAdminTransactions(txQuery),getReports(),getAdminListings(listingQuery),getAdminAuditLogs(logQuery),getAdminCampuses()]);setMembers(m);setAllMembers(am);setUsers(u);setTxs(t);setReports(r.filter(x=>x.status==='open'));setListings(l);setLogs(a);setCampuses(cs); if(selectedCampus){setCourses(await getAdminCourses(selectedCampus))}else{setCourses([])}}catch(e){setError(e instanceof Error?e.message:'Unable to load admin console')}};
 useEffect(()=>{void load()},[selectedCampus]);
 const approve=async(id:number)=>{setBusy(id);try{await approveCampusMember(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to approve membership')}finally{setBusy(null)}};
 const revoke=async(id:number)=>{if(!window.confirm('Revoke this campus membership? The student will need approval again.'))return;setBusy(id);try{await revokeCampusMember(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to revoke membership')}finally{setBusy(null)}};
 const toggle=async(u:UserRow)=>{setBusy(u.id);try{await setAdminUserStatus(u.id,!u.active);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update user')}finally{setBusy(null)}};
 const resolve=async(id:number,status:'resolved'|'dismissed')=>{setBusy(id);try{await resolveReport(id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to resolve report')}finally{setBusy(null)}};
 const moderate=async(id:number)=>{if(!window.confirm('Remove this listing from the marketplace?'))return;setBusy(id);try{await moderateListing(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to moderate listing')}finally{setBusy(null)}};
 const addCourse=async()=>{if(!selectedCampus||!courseForm.code.trim()||!courseForm.name.trim())return;setBusy(-50);setError('');try{await createAdminCourse(selectedCampus,courseForm);setCourseForm({code:'',name:'',semester:''});setCourses(await getAdminCourses(selectedCampus));}catch(e){setError(e instanceof Error?e.message:'Unable to create course')}finally{setBusy(null)}};
 return <AppShell active="Admin"><div className="page-header"><div><div className="eyebrow">OPERATIONS</div><h1>Admin Console</h1><p className="muted small">Manage verification, reports, listings, users, transactions and audit history.</p></div><div className="page-actions"><Link className="btn btn-ghost" href="/admin/campuses">Campus directory</Link><Link className="btn btn-ghost" href="/admin/reports">Reports</Link></div></div>{error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Pending campus verification</h2><span className="muted small">{members.length} pending</span></div>{members.map(m=><div className="seller-list-row" key={m.id}><div><strong>{m.name}</strong><div className="muted small">{m.email} · {m.campus_name}</div><span className="muted small">Method: {m.verification_method}</span></div><button className="btn btn-primary" disabled={busy===m.id} onClick={()=>approve(m.id)}>{busy===m.id?'Approving...':'Approve'}</button></div>)}{!members.length&&<div className="empty-state"><strong>No pending verifications</strong><span>Institutional email members can be auto-verified; other requests appear here.</span></div>}</section>
 <section className="panel"><div className="panel-head"><h2>Open reports</h2><span className="muted small">{reports.length}</span></div>{reports.slice(0,8).map(r=><div className="offer-management-row" key={r.id}><div><strong>{r.target_type} #{r.target_id}</strong><p>{r.reason}</p><span>{r.notes||'No notes'}</span></div><div className="offer-actions"><button className="btn btn-ghost" onClick={()=>resolve(r.id,'dismissed')}>Dismiss</button><button className="btn btn-primary" onClick={()=>resolve(r.id,'resolved')}>Resolve</button>{r.target_type==='listing'&&<button className="btn btn-ghost" onClick={()=>moderate(r.target_id)}>Remove listing</button>}</div></div>)}{!reports.length&&<div className="empty-state"><strong>No open reports</strong><span>Reported content will appear here.</span></div>}</section></div>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Verified campus memberships</h2><span className="muted small">Revoke access when a student should no longer use a campus marketplace.</span></div></div>{allMembers.filter(m=>m.verified).slice(0,30).map(m=><div className="seller-list-row" key={m.id}><div><strong>{m.name}</strong><div className="muted small">{m.email} · {m.campus_name} · {m.verification_method}</div></div><button className="btn btn-ghost" disabled={busy===m.id} onClick={()=>revoke(m.id)}>{busy===m.id?"Revoking...":"Revoke"}</button></div>)}{!allMembers.some(m=>m.verified)&&<div className="empty-state"><strong>No verified memberships</strong></div>}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Users</h2><span className="muted small">Search by name, email or phone</span></div><div style={{display:'flex',gap:8}}><input value={userQuery} onChange={e=>setUserQuery(e.target.value)} placeholder="Search users"/><button className="btn btn-ghost" onClick={load}>Search</button></div></div>{users.slice(0,30).map(u=><div className="seller-list-row" key={u.id}><div><strong>{u.name}</strong><div className="muted small">{u.email}{u.phone?` · ${u.phone}`:''} · {u.role}</div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span className={`transaction-status ${u.active?'active':''}`}>{u.active?'active':'inactive'}</span><button className="btn btn-ghost" disabled={busy===u.id} onClick={()=>toggle(u)}>{u.active?'Deactivate':'Activate'}</button></div></div>)}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Listing moderation</h2><span className="muted small">Search listings and remove prohibited/problematic content</span></div><div style={{display:'flex',gap:8}}><input value={listingQuery} onChange={e=>setListingQuery(e.target.value)} placeholder="Title, seller or campus"/><button className="btn btn-ghost" onClick={load}>Search</button></div></div>{listings.slice(0,30).map(l=><div className="seller-list-row" key={l.id}><div><strong>#{l.id} · {l.title}</strong><div className="muted small">{l.seller_name} · {l.campus_name} · ₹{Number(l.price).toLocaleString('en-IN')}</div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span className={`transaction-status ${l.status==='active'?'active':''}`}>{l.status}</span>{l.status==='active'&&<button className="btn btn-ghost" onClick={()=>moderate(l.id)}>Remove</button>}</div></div>)}{!listings.length&&<div className="empty-state"><strong>No matching listings</strong></div>}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Transactions</h2><span className="muted small">Lookup by transaction id or listing title</span></div><div style={{display:'flex',gap:8}}><input value={txQuery} onChange={e=>setTxQuery(e.target.value)} placeholder="Transaction ID or title"/><button className="btn btn-ghost" onClick={load}>Search</button></div></div>{txs.slice(0,30).map(t=><div className="seller-list-row" key={t.id}><div><strong>#{t.id} · {t.listing_title}</strong><div className="muted small">Buyer: {t.buyer_name} · {t.buyer_email} · Seller #{t.seller_id}</div></div><div style={{textAlign:'right'}}><strong>₹{Number(t.agreed_price).toLocaleString('en-IN')}</strong><div className="muted small">{t.status}</div></div></div>)}{!txs.length&&<div className="empty-state"><strong>No transactions</strong></div>}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Course catalog</h2><span className="muted small">Create and maintain course records for student discovery.</span></div><select value={selectedCampus ?? ''} onChange={e=>setSelectedCampus(e.target.value?Number(e.target.value):null)}><option value="">Select campus</option>{campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{selectedCampus&&<><div className="form-grid" style={{marginBottom:12}}><label>Code<input value={courseForm.code} onChange={e=>setCourseForm({...courseForm,code:e.target.value})} placeholder="CS401"/></label><label>Name<input value={courseForm.name} onChange={e=>setCourseForm({...courseForm,name:e.target.value})} placeholder="Distributed Systems"/></label><label>Semester<input value={courseForm.semester} onChange={e=>setCourseForm({...courseForm,semester:e.target.value})} placeholder="Semester 7"/></label></div><button className="btn btn-primary" disabled={busy===-50||!courseForm.code.trim()||!courseForm.name.trim()} onClick={addCourse}>{busy===-50?'Creating...':'Add course'}</button><div style={{marginTop:14}}>{courses.slice(0,30).map(c=><div className="seller-list-row" key={c.id}><div><strong>{c.code} · {c.name}</strong><div className="muted small">{c.semester||'Current semester'}</div></div></div>)}{!courses.length&&<div className="empty-state"><strong>No courses for this campus</strong></div>}</div></>}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Audit history</h2><span className="muted small">Recent administrative and lifecycle actions</span></div><div style={{display:'flex',gap:8}}><input value={logQuery} onChange={e=>setLogQuery(e.target.value)} placeholder="Action, resource or detail"/><button className="btn btn-ghost" onClick={load}>Search</button></div></div>{logs.slice(0,30).map(l=><div className="seller-list-row" key={l.id}><div><strong>{l.action}</strong><div className="muted small">{l.resource_type} #{l.resource_id} · actor #{l.actor_user_id ?? 'system'}</div><span className="muted small">{l.detail || 'No detail'}</span></div><span className="muted small">{new Date(l.created_at).toLocaleString('en-IN')}</span></div>)}{!logs.length&&<div className="empty-state"><strong>No audit events</strong></div>}</section>
 </AppShell>;
}
